/* ==========================================================================
   TRUST ME BRO - topics.js
   Seed corpus: 391 tier-list topics across 16 categories.
   Shape: { t: title, c: category, i: [items, best -> worst] }
   app.js turns each into a post - toTiers() spreads `i` across S-D, and the
   author/votes/comments/timestamp are derived deterministically from the id.
   Loaded before app.js; must stay a plain script (no modules) so the site
   keeps working over file://.
   ========================================================================== */

window.TRENDY_TOPICS = [
  { t: "Fast Food Brands", c: "Fast Food", i: ["McDonald's", "Wendy's", "Chick-fil-A", "Burger King", "Subway"] },
  { t: "Pizza Chains", c: "Fast Food", i: ["Domino's", "Papa John's", "Pizza Hut", "Little Caesars", "Chuck E. Cheese"] },
  { t: "Coffee Chains", c: "Fast Food", i: ["Starbucks", "Dunkin'", "Tim Hortons", "Peet's Coffee", "Caribou Coffee"] },
  { t: "Soda Brands", c: "Fast Food", i: ["Coca-Cola", "Dr Pepper", "Pepsi", "Sprite", "Mountain Dew"] },
  { t: "Candy Bars", c: "Fast Food", i: ["Snickers", "Twix", "Kit Kat", "Milky Way", "Almond Joy"] },
  { t: "Potato Chip Brands", c: "Fast Food", i: ["Lay's", "Doritos", "Pringles", "Ruffles", "Fritos"] },
  { t: "Breakfast Cereals", c: "Fast Food", i: ["Cinnamon Toast Crunch", "Frosted Flakes", "Lucky Charms", "Cheerios", "Raisin Bran"] },
  { t: "Ice Cream Brands", c: "Fast Food", i: ["Ben & Jerry's", "Haagen-Dazs", "Talenti", "Breyers", "Blue Bunny"] },
  { t: "Pizza Toppings", c: "Fast Food", i: ["Pepperoni", "Sausage", "Mushroom", "Onion", "Anchovy"] },
  { t: "Burger Toppings", c: "Fast Food", i: ["Cheese", "Bacon", "Lettuce", "Pickles", "Raw Onion"] },
  { t: "French Fry Styles", c: "Fast Food", i: ["Crinkle Cut", "Curly Fries", "Waffle Fries", "Steak Fries", "Shoestring"] },
  { t: "Chicken Sandwiches", c: "Fast Food", i: ["Chick-fil-A", "Popeyes", "Wendy's", "KFC", "McDonald's"] },
  { t: "Mexican Fast Food", c: "Fast Food", i: ["Chipotle", "Taco Bell", "Qdoba", "Del Taco", "Moe's"] },
  { t: "Breakfast Foods", c: "Fast Food", i: ["Pancakes", "Bacon", "French Toast", "Waffles", "Oatmeal"] },
  { t: "Donut Flavors", c: "Fast Food", i: ["Glazed", "Boston Cream", "Chocolate Frosted", "Jelly Filled", "Old Fashioned"] },
  { t: "Cookie Brands", c: "Fast Food", i: ["Oreo", "Chips Ahoy", "Girl Scout Cookies", "Nutter Butter", "Fig Newtons"] },
  { t: "Energy Drinks", c: "Fast Food", i: ["Red Bull", "Monster", "Celsius", "Bang", "Rockstar"] },
  { t: "Sandwich Chains", c: "Fast Food", i: ["Jimmy John's", "Jersey Mike's", "Firehouse Subs", "Subway", "Quiznos"] },
  { t: "Milkshake Flavors", c: "Fast Food", i: ["Chocolate", "Vanilla", "Cookies and Cream", "Strawberry", "Banana"] },
  { t: "Condiments", c: "Fast Food", i: ["Ketchup", "Ranch", "Mayonnaise", "Mustard", "Relish"] },
  { t: "Pasta Dishes", c: "Fast Food", i: ["Lasagna", "Spaghetti", "Fettuccine Alfredo", "Mac and Cheese", "Ravioli"] },
  { t: "Chocolate Brands", c: "Fast Food", i: ["Lindt", "Ghirardelli", "Cadbury", "Hershey's", "Toblerone"] },
  { t: "Chicken Wing Flavors", c: "Fast Food", i: ["Buffalo", "Honey BBQ", "Garlic Parmesan", "Lemon Pepper", "Plain"] },
  { t: "Steakhouse Chains", c: "Fast Food", i: ["Ruth's Chris", "Texas Roadhouse", "Outback", "LongHorn", "Golden Corral"] },
  { t: "Snack Foods", c: "Fast Food", i: ["Popcorn", "Pretzels", "Cheez-Its", "Goldfish", "Trail Mix"] },
  { t: "Dream Vacation Destinations", c: "Travel", i: ["Japan", "Italy", "Greece", "Thailand", "Iceland"] },
  { t: "Countries", c: "Travel", i: ["Japan", "Italy", "Canada", "Brazil", "Australia"] },
  { t: "European Cities", c: "Travel", i: ["Paris", "Rome", "Barcelona", "Amsterdam", "Berlin"] },
  { t: "US Cities", c: "Travel", i: ["New York", "Chicago", "San Francisco", "Nashville", "Los Angeles"] },
  { t: "Theme Parks", c: "Travel", i: ["Disney World", "Universal Studios", "Disneyland", "Cedar Point", "Six Flags"] },
  { t: "Airlines", c: "Travel", i: ["Delta", "Emirates", "Southwest", "United", "Spirit"] },
  { t: "Hotel Chains", c: "Travel", i: ["Four Seasons", "Marriott", "Hilton", "Holiday Inn", "Motel 6"] },
  { t: "National Parks", c: "Travel", i: ["Yellowstone", "Yosemite", "Grand Canyon", "Zion", "Acadia"] },
  { t: "Wonders of the World", c: "Travel", i: ["Great Wall of China", "Machu Picchu", "Taj Mahal", "Colosseum", "Christ the Redeemer"] },
  { t: "Beach Destinations", c: "Travel", i: ["Maldives", "Bora Bora", "Hawaii", "Bali", "Cancun"] },
  { t: "Islands", c: "Travel", i: ["Hawaii", "Santorini", "Bali", "Fiji", "Sicily"] },
  { t: "Ski Destinations", c: "Travel", i: ["Aspen", "Whistler", "Zermatt", "Vail", "Park City"] },
  { t: "Asian Countries", c: "Travel", i: ["Japan", "South Korea", "Thailand", "Vietnam", "India"] },
  { t: "US States", c: "Travel", i: ["California", "Colorado", "Hawaii", "Texas", "Florida"] },
  { t: "Road Trip Routes", c: "Travel", i: ["Pacific Coast Highway", "Route 66", "Blue Ridge Parkway", "Great Ocean Road", "Ring Road Iceland"] },
  { t: "Ways to Travel", c: "Travel", i: ["Airplane", "Train", "Car", "Cruise Ship", "Bus"] },
  { t: "Famous Landmarks", c: "Travel", i: ["Eiffel Tower", "Statue of Liberty", "Big Ben", "Sydney Opera House", "Leaning Tower of Pisa"] },
  { t: "Cruise Destinations", c: "Travel", i: ["Caribbean", "Alaska", "Mediterranean", "Norwegian Fjords", "Bahamas"] },
  { t: "Airport Experiences", c: "Travel", i: ["Singapore Changi", "Tokyo Haneda", "Amsterdam Schiphol", "Atlanta", "Newark"] },
  { t: "Canadian Cities", c: "Travel", i: ["Vancouver", "Toronto", "Montreal", "Quebec City", "Calgary"] },
  { t: "South American Countries", c: "Travel", i: ["Brazil", "Argentina", "Peru", "Chile", "Colombia"] },
  { t: "African Destinations", c: "Travel", i: ["Egypt", "South Africa", "Morocco", "Kenya", "Tanzania"] },
  { t: "Vacation Types", c: "Travel", i: ["Beach Resort", "Road Trip", "City Break", "Camping", "Cruise"] },
  { t: "Travel Seasons", c: "Travel", i: ["Summer", "Fall", "Spring", "Winter Holidays", "Rainy Season"] },
  { t: "Luggage Brands", c: "Travel", i: ["Away", "Samsonite", "Tumi", "Rimowa", "American Tourister"] },
  { t: "Days of the Week", c: "Life", i: ["Friday", "Saturday", "Sunday", "Thursday", "Monday"] },
  { t: "Seasons", c: "Life", i: ["Fall", "Summer", "Spring", "Winter", "Mud Season"] },
  { t: "Holidays", c: "Life", i: ["Christmas", "Thanksgiving", "Halloween", "New Year's Eve", "Valentine's Day"] },
  { t: "School Subjects", c: "Life", i: ["Art", "History", "English", "Science", "Math"] },
  { t: "Household Chores", c: "Life", i: ["Laundry", "Vacuuming", "Dishes", "Bathroom Cleaning", "Yard Work"] },
  { t: "Board Games", c: "Life", i: ["Catan", "Ticket to Ride", "Clue", "Scrabble", "Monopoly"] },
  { t: "Hobbies", c: "Life", i: ["Reading", "Cooking", "Hiking", "Gardening", "Knitting"] },
  { t: "Jobs", c: "Life", i: ["Doctor", "Teacher", "Firefighter", "Accountant", "Telemarketer"] },
  { t: "Types of Weather", c: "Life", i: ["Sunny", "Light Snow", "Cloudy", "Rain", "Humid Heat"] },
  { t: "Months of the Year", c: "Life", i: ["December", "June", "October", "March", "February"] },
  { t: "Sleep Schedules", c: "Life", i: ["Eight Hours", "Early Bird", "Night Owl", "Afternoon Nap", "All Nighter"] },
  { t: "Ways to Exercise", c: "Life", i: ["Walking", "Swimming", "Weightlifting", "Running", "Burpees"] },
  { t: "Social Media Apps", c: "Life", i: ["YouTube", "Instagram", "TikTok", "Reddit", "LinkedIn"] },
  { t: "Streaming Services", c: "Life", i: ["Netflix", "HBO Max", "Disney Plus", "Hulu", "Peacock"] },
  { t: "Video Game Consoles", c: "Life", i: ["PlayStation 5", "Nintendo Switch", "Xbox Series X", "Steam Deck", "Wii"] },
  { t: "Team Sports", c: "Life", i: ["Soccer", "Basketball", "Football", "Baseball", "Cricket"] },
  { t: "Musical Instruments", c: "Life", i: ["Guitar", "Piano", "Drums", "Violin", "Recorder"] },
  { t: "Movie Genres", c: "Life", i: ["Comedy", "Action", "Thriller", "Horror", "Documentary"] },
  { t: "Times of Day", c: "Life", i: ["Evening", "Morning", "Late Night", "Afternoon", "Early Morning"] },
  { t: "Modes of Transportation", c: "Life", i: ["Car", "Bicycle", "Train", "Subway", "Scooter"] },
  { t: "Phone Brands", c: "Life", i: ["iPhone", "Samsung", "Google Pixel", "OnePlus", "Motorola"] },
  { t: "Car Brands", c: "Life", i: ["Toyota", "Honda", "BMW", "Ford", "Chrysler"] },
  { t: "Types of Shoes", c: "Life", i: ["Sneakers", "Boots", "Sandals", "Dress Shoes", "Crocs"] },
  { t: "Ways to Wake Up", c: "Life", i: ["Natural Light", "Phone Alarm", "Coffee Smell", "Snooze Button", "Loud Alarm Clock"] },
  { t: "Card Games", c: "Life", i: ["Poker", "Uno", "Blackjack", "Solitaire", "Go Fish"] },
  { t: "Best Pets", c: "Animals", i: ["Dog", "Cat", "Parrot", "Hamster", "Goldfish"] },
  { t: "Dog Breeds", c: "Animals", i: ["Golden Retriever", "Labrador", "German Shepherd", "Beagle", "Chihuahua"] },
  { t: "Cat Breeds", c: "Animals", i: ["Maine Coon", "Siamese", "Persian", "Bengal", "Sphynx"] },
  { t: "Big Cats", c: "Animals", i: ["Tiger", "Lion", "Leopard", "Cheetah", "Cougar"] },
  { t: "Ocean Animals", c: "Animals", i: ["Dolphin", "Whale", "Sea Turtle", "Octopus", "Jellyfish"] },
  { t: "Birds", c: "Animals", i: ["Eagle", "Owl", "Penguin", "Parrot", "Pigeon"] },
  { t: "Farm Animals", c: "Animals", i: ["Horse", "Cow", "Pig", "Chicken", "Goat"] },
  { t: "Zoo Animals", c: "Animals", i: ["Elephant", "Giraffe", "Panda", "Zebra", "Hippo"] },
  { t: "Reptiles", c: "Animals", i: ["Chameleon", "Sea Turtle", "Gecko", "Iguana", "Crocodile"] },
  { t: "Insects", c: "Animals", i: ["Butterfly", "Ladybug", "Bee", "Ant", "Mosquito"] },
  { t: "Bears", c: "Animals", i: ["Panda", "Polar Bear", "Grizzly Bear", "Black Bear", "Sun Bear"] },
  { t: "Sharks", c: "Animals", i: ["Great White", "Hammerhead", "Whale Shark", "Tiger Shark", "Nurse Shark"] },
  { t: "Australian Animals", c: "Animals", i: ["Kangaroo", "Koala", "Wombat", "Platypus", "Emu"] },
  { t: "Arctic Animals", c: "Animals", i: ["Polar Bear", "Penguin", "Arctic Fox", "Walrus", "Seal"] },
  { t: "Rainforest Animals", c: "Animals", i: ["Jaguar", "Toucan", "Sloth", "Poison Dart Frog", "Tarantula"] },
  { t: "Small Pets", c: "Animals", i: ["Guinea Pig", "Hamster", "Rabbit", "Gerbil", "Ferret"] },
  { t: "Extinct Animals", c: "Animals", i: ["Tyrannosaurus Rex", "Woolly Mammoth", "Saber Tooth Tiger", "Dodo", "Giant Sloth"] },
  { t: "Horses and Relatives", c: "Animals", i: ["Horse", "Zebra", "Pony", "Donkey", "Mule"] },
  { t: "Primates", c: "Animals", i: ["Gorilla", "Orangutan", "Chimpanzee", "Lemur", "Baboon"] },
  { t: "Freshwater Fish", c: "Animals", i: ["Trout", "Bass", "Koi", "Catfish", "Carp"] },
  { t: "Nocturnal Animals", c: "Animals", i: ["Owl", "Fox", "Bat", "Raccoon", "Opossum"] },
  { t: "Backyard Animals", c: "Animals", i: ["Squirrel", "Rabbit", "Deer", "Chipmunk", "Skunk"] },
  { t: "Snakes", c: "Animals", i: ["Ball Python", "Corn Snake", "King Cobra", "Rattlesnake", "Anaconda"] },
  { t: "Baby Animals", c: "Animals", i: ["Puppy", "Kitten", "Duckling", "Piglet", "Tadpole"] },
  { t: "Desert Animals", c: "Animals", i: ["Camel", "Meerkat", "Fennec Fox", "Roadrunner", "Scorpion"] },
  { t: "Game Consoles", c: "Games", i: ["PlayStation 2", "Nintendo Switch", "Xbox 360", "PlayStation 5", "Wii U"] },
  { t: "Nintendo Franchises", c: "Games", i: ["Zelda", "Mario", "Metroid", "Pokemon", "Animal Crossing"] },
  { t: "Racing Games", c: "Games", i: ["Mario Kart 8", "Forza Horizon 5", "Gran Turismo 7", "Need for Speed", "Burnout Paradise"] },
  { t: "Fighting Games", c: "Games", i: ["Super Smash Bros", "Street Fighter", "Tekken", "Mortal Kombat", "Injustice"] },
  { t: "Shooter Franchises", c: "Games", i: ["Halo", "Call of Duty", "Counter-Strike", "Battlefield", "Overwatch"] },
  { t: "Open World Games", c: "Games", i: ["Breath of the Wild", "Elden Ring", "Red Dead 2", "Skyrim", "Far Cry 6"] },
  { t: "Mario Games", c: "Games", i: ["Super Mario 64", "Super Mario Odyssey", "Super Mario World", "Super Mario Galaxy", "Super Mario Sunshine"] },
  { t: "Zelda Games", c: "Games", i: ["Ocarina of Time", "Breath of the Wild", "Majora's Mask", "Wind Waker", "Skyward Sword"] },
  { t: "Pokemon Generations", c: "Games", i: ["Gen 2", "Gen 1", "Gen 3", "Gen 5", "Gen 8"] },
  { t: "Indie Games", c: "Games", i: ["Hollow Knight", "Stardew Valley", "Undertale", "Celeste", "Among Us"] },
  { t: "Battle Royale Games", c: "Games", i: ["Fortnite", "Apex Legends", "PUBG", "Warzone", "Fall Guys"] },
  { t: "Mobile Games", c: "Games", i: ["Clash of Clans", "Candy Crush", "Pokemon GO", "Subway Surfers", "Angry Birds"] },
  { t: "Game Studios", c: "Games", i: ["Nintendo", "Rockstar Games", "FromSoftware", "Valve", "Ubisoft"] },
  { t: "Horror Games", c: "Games", i: ["Resident Evil 4", "Silent Hill 2", "Amnesia", "Outlast", "Five Nights at Freddy's"] },
  { t: "Sports Games", c: "Games", i: ["NBA 2K", "FIFA", "Madden NFL", "Rocket League", "Tony Hawk"] },
  { t: "Minecraft Mobs", c: "Games", i: ["Ender Dragon", "Enderman", "Creeper", "Zombie", "Silverfish"] },
  { t: "Grand Theft Auto Games", c: "Games", i: ["GTA San Andreas", "GTA V", "GTA Vice City", "GTA IV", "GTA III"] },
  { t: "Souls Games", c: "Games", i: ["Elden Ring", "Bloodborne", "Dark Souls", "Sekiro", "Dark Souls II"] },
  { t: "Party Games", c: "Games", i: ["Mario Party", "Jackbox", "Among Us", "Overcooked", "Wii Sports"] },
  { t: "Handheld Consoles", c: "Games", i: ["Nintendo DS", "Game Boy Advance", "PSP", "Nintendo 3DS", "PS Vita"] },
  { t: "Strategy Games", c: "Games", i: ["Civilization VI", "StarCraft II", "Age of Empires II", "Total War", "Command and Conquer"] },
  { t: "Survival Games", c: "Games", i: ["Minecraft", "Terraria", "Valheim", "Rust", "Ark Survival"] },
  { t: "Video Game Villains", c: "Games", i: ["Bowser", "Ganondorf", "Sephiroth", "Dr Eggman", "Wario"] },
  { t: "MMORPGs", c: "Games", i: ["World of Warcraft", "Final Fantasy XIV", "Runescape", "Guild Wars 2", "New World"] },
  { t: "Gaming Peripherals", c: "Games", i: ["Xbox Controller", "DualSense", "Elite Controller", "Joy-Cons", "Wii Remote"] },
  { t: "Shonen Anime", c: "Anime", i: ["Fullmetal Alchemist", "Hunter x Hunter", "One Piece", "Naruto", "Bleach"] },
  { t: "Studio Ghibli Films", c: "Anime", i: ["Spirited Away", "Princess Mononoke", "My Neighbor Totoro", "Howl's Moving Castle", "Ponyo"] },
  { t: "Mecha Anime", c: "Anime", i: ["Neon Genesis Evangelion", "Gurren Lagann", "Code Geass", "Gundam", "Darling in the Franxx"] },
  { t: "Sports Anime", c: "Anime", i: ["Haikyuu", "Slam Dunk", "Kuroko's Basketball", "Yuri on Ice", "Free"] },
  { t: "Romance Anime", c: "Anime", i: ["Toradora", "Your Lie in April", "Fruits Basket", "Horimiya", "Kaguya-sama"] },
  { t: "Anime Openings", c: "Anime", i: ["Guren no Yumiya", "Tank!", "A Cruel Angel's Thesis", "Gurenge", "Blue Bird"] },
  { t: "Pokemon Starters", c: "Anime", i: ["Charmander", "Bulbasaur", "Squirtle", "Cyndaquil", "Chespin"] },
  { t: "Dragon Ball Sagas", c: "Anime", i: ["Cell Saga", "Frieza Saga", "Buu Saga", "Saiyan Saga", "Garlic Jr Saga"] },
  { t: "Anime Main Characters", c: "Anime", i: ["Goku", "Luffy", "Naruto", "Ichigo", "Eren Yeager"] },
  { t: "Anime Streaming Services", c: "Anime", i: ["Crunchyroll", "Netflix", "Hulu", "Amazon Prime", "Funimation"] },
  { t: "Isekai Anime", c: "Anime", i: ["Re:Zero", "Mushoku Tensei", "Konosuba", "Sword Art Online", "Shield Hero"] },
  { t: "Anime Movies", c: "Anime", i: ["Your Name", "Akira", "A Silent Voice", "Weathering With You", "Mugen Train"] },
  { t: "Modern Shonen Anime", c: "Anime", i: ["Demon Slayer", "Jujutsu Kaisen", "My Hero Academia", "Chainsaw Man", "Black Clover"] },
  { t: "Anime Villains", c: "Anime", i: ["Light Yagami", "Frieza", "Aizen", "Madara", "Shigaraki"] },
  { t: "Naruto Characters", c: "Anime", i: ["Kakashi", "Itachi", "Naruto", "Sasuke", "Sakura"] },
  { t: "One Piece Arcs", c: "Anime", i: ["Marineford", "Enies Lobby", "Water 7", "Alabasta", "Dressrosa"] },
  { t: "Seinen Anime", c: "Anime", i: ["Berserk", "Monster", "Vinland Saga", "Psycho-Pass", "Tokyo Ghoul"] },
  { t: "Attack on Titan Seasons", c: "Anime", i: ["Season 3", "Season 4", "Season 1", "Season 2", "Season 3 Part 1"] },
  { t: "Slice of Life Anime", c: "Anime", i: ["K-On", "Nichijou", "Barakamon", "Yuru Camp", "Non Non Biyori"] },
  { t: "Anime Studios", c: "Anime", i: ["Ufotable", "MAPPA", "Madhouse", "Bones", "Toei Animation"] },
  { t: "Pokemon Types", c: "Anime", i: ["Dragon", "Water", "Fire", "Steel", "Bug"] },
  { t: "Anime Swords", c: "Anime", i: ["Zangetsu", "Tessaiga", "Nichirin Blade", "Murasame", "Elucidator"] },
  { t: "Comedy Anime", c: "Anime", i: ["Gintama", "One Punch Man", "Grand Blue", "Nichijou", "Saiki K"] },
  { t: "Death Note Characters", c: "Anime", i: ["L", "Light Yagami", "Ryuk", "Near", "Misa"] },
  { t: "Magical Girl Anime", c: "Anime", i: ["Madoka Magica", "Sailor Moon", "Cardcaptor Sakura", "Precure", "Tokyo Mew Mew"] },
  { t: "Classic Meme Formats", c: "Memes", i: ["Distracted Boyfriend", "Drake Format", "Doge", "Bad Luck Brian", "Success Kid"] },
  { t: "Emojis", c: "Memes", i: ["Skull", "Crying Laughing", "Fire", "Thumbs Up", "Eggplant"] },
  { t: "Internet Slang", c: "Memes", i: ["LOL", "Bruh", "Sus", "Yeet", "Cringe"] },
  { t: "Viral Videos", c: "Memes", i: ["Charlie Bit Me", "Rickroll", "Gangnam Style", "Harlem Shake", "Baby Shark"] },
  { t: "Reaction Images", c: "Memes", i: ["Surprised Pikachu", "This Is Fine", "Confused Math Lady", "Side Eye Chloe", "Blinking White Guy"] },
  { t: "YouTube Genres", c: "Memes", i: ["Video Essays", "Let's Plays", "Reaction Videos", "Unboxing", "Prank Videos"] },
  { t: "Group Chat Habits", c: "Memes", i: ["Sending Memes", "Reacting to Texts", "Voice Notes", "Leaving on Read", "Double Texting"] },
  { t: "Texting Habits", c: "Memes", i: ["Short Replies", "GIF Replies", "All Lowercase", "Typing Then Stopping", "One Word Answers"] },
  { t: "Meme Animals", c: "Memes", i: ["Doge", "Grumpy Cat", "Nyan Cat", "Cheems", "Bongo Cat"] },
  { t: "TikTok Trends", c: "Memes", i: ["Renegade", "Get Ready With Me", "POV Videos", "Lip Sync", "Dance Challenges"] },
  { t: "Meme Sounds", c: "Memes", i: ["Bruh Sound Effect", "Vine Boom", "Sad Violin", "Windows XP Error", "Airhorn"] },
  { t: "Old Internet Sites", c: "Memes", i: ["YouTube", "MySpace", "Newgrounds", "Tumblr", "Vine"] },
  { t: "Messaging Apps", c: "Memes", i: ["WhatsApp", "Discord", "Telegram", "Snapchat", "Messenger"] },
  { t: "Meme Phrases", c: "Memes", i: ["It's Over 9000", "Never Gonna Give", "Deez Nuts", "Ok Boomer", "No Cap"] },
  { t: "Streamer Platforms", c: "Memes", i: ["YouTube", "Twitch", "Kick", "TikTok Live", "Facebook Gaming"] },
  { t: "Reddit Subreddits", c: "Memes", i: ["r/AskReddit", "r/memes", "r/AITA", "r/gaming", "r/funny"] },
  { t: "Meme Wars", c: "Memes", i: ["Cat vs Dog", "Android vs iPhone", "PC vs Console", "Pineapple Pizza", "Tabs vs Spaces"] },
  { t: "Discord Behaviors", c: "Memes", i: ["Sharing Memes", "Voice Chatting", "Custom Emojis", "Pinging Everyone", "Reading Announcements"] },
  { t: "Meme Characters", c: "Memes", i: ["Shrek", "Pepe", "Wojak", "Trollface", "Big Chungus"] },
  { t: "Vine Classics", c: "Memes", i: ["Road Work Ahead", "Two Bros Hot Tub", "Look at All Those", "Adam Ate My Fry", "Hurricane Katrina"] },
  { t: "Online Arguments", c: "Memes", i: ["Best Anime", "Best Pizza Topping", "Cereal Is Soup", "Best Console", "Toilet Paper Direction"] },
  { t: "Meme Dances", c: "Memes", i: ["Gangnam Style", "Floss", "Harlem Shake", "Orange Justice", "Default Dance"] },
  { t: "Phone Notifications", c: "Memes", i: ["Text Message", "DM Notification", "Group Chat Ping", "App Update", "Screen Time Report"] },
  { t: "Streaming Chat Terms", c: "Memes", i: ["Pog", "KEKW", "Copium", "Sadge", "First"] },
  { t: "Laptop Brands", c: "Tech", i: ["MacBook", "ThinkPad", "Dell XPS", "ASUS ZenBook", "HP Pavilion"] },
  { t: "Web Browsers", c: "Tech", i: ["Chrome", "Firefox", "Safari", "Edge", "Opera"] },
  { t: "Operating Systems", c: "Tech", i: ["Windows 11", "macOS", "Linux", "Android", "iOS"] },
  { t: "Headphone Brands", c: "Tech", i: ["Sony", "Bose", "AirPods", "Sennheiser", "Beats"] },
  { t: "Search Engines", c: "Tech", i: ["Google", "Bing", "DuckDuckGo", "Yahoo", "Ask Jeeves"] },
  { t: "Programming Languages", c: "Tech", i: ["Python", "JavaScript", "TypeScript", "Java", "PHP"] },
  { t: "Keyboard Brands", c: "Tech", i: ["Keychron", "Logitech", "Razer", "Corsair", "Redragon"] },
  { t: "Smart Speakers", c: "Tech", i: ["Amazon Echo", "Google Nest", "Apple HomePod", "Sonos One", "Bose Home"] },
  { t: "Big Tech Companies", c: "Tech", i: ["Apple", "Google", "Microsoft", "Amazon", "Meta"] },
  { t: "Music Streaming Apps", c: "Tech", i: ["Spotify", "Apple Music", "YouTube Music", "Tidal", "Deezer"] },
  { t: "GPU Brands", c: "Tech", i: ["NVIDIA", "AMD", "Intel Arc", "EVGA", "Zotac"] },
  { t: "Smartwatches", c: "Tech", i: ["Apple Watch", "Galaxy Watch", "Garmin", "Fitbit", "Amazfit"] },
  { t: "Cloud Storage Services", c: "Tech", i: ["Google Drive", "Dropbox", "iCloud", "OneDrive", "Box"] },
  { t: "Video Call Apps", c: "Tech", i: ["Zoom", "Google Meet", "FaceTime", "Microsoft Teams", "Skype"] },
  { t: "Electric Car Brands", c: "Tech", i: ["Tesla", "Rivian", "Hyundai", "Ford", "Nissan"] },
  { t: "Code Editors", c: "Tech", i: ["VS Code", "JetBrains IDEs", "Neovim", "Sublime Text", "Notepad Plus Plus"] },
  { t: "Camera Brands", c: "Tech", i: ["Sony", "Canon", "Nikon", "Fujifilm", "GoPro"] },
  { t: "Gaming Laptops", c: "Tech", i: ["ASUS ROG", "Razer Blade", "Alienware", "MSI", "Acer Predator"] },
  { t: "Tablet Brands", c: "Tech", i: ["iPad", "Galaxy Tab", "Surface Pro", "Amazon Fire", "Lenovo Tab"] },
  { t: "Payment Apps", c: "Tech", i: ["Apple Pay", "PayPal", "Venmo", "Cash App", "Zelle"] },
  { t: "Note Taking Apps", c: "Tech", i: ["Notion", "Obsidian", "Apple Notes", "OneNote", "Evernote"] },
  { t: "Wireless Earbuds", c: "Tech", i: ["AirPods Pro", "Sony WF-1000XM5", "Galaxy Buds", "Bose QuietComfort", "Pixel Buds"] },
  { t: "Ride Sharing Apps", c: "Tech", i: ["Uber", "Lyft", "Bolt", "Grab", "Didi"] },
  { t: "Marvel Movies", c: "Movies", i: ["Avengers: Endgame", "Iron Man", "Black Panther", "Thor", "Eternals"] },
  { t: "Pixar Movies", c: "Movies", i: ["Toy Story", "Up", "Finding Nemo", "Ratatouille", "Cars 2"] },
  { t: "Star Wars Movies", c: "Movies", i: ["Empire Strikes Back", "A New Hope", "Return of the Jedi", "The Force Awakens", "The Phantom Menace"] },
  { t: "Horror Movies", c: "Movies", i: ["The Shining", "The Exorcist", "Halloween", "Scream", "Annabelle"] },
  { t: "Disney Animated Classics", c: "Movies", i: ["The Lion King", "Beauty and the Beast", "Aladdin", "Mulan", "Pocahontas"] },
  { t: "Christmas Movies", c: "Movies", i: ["Home Alone", "Elf", "Die Hard", "The Grinch", "The Polar Express"] },
  { t: "Batman Actors", c: "Movies", i: ["Christian Bale", "Michael Keaton", "Robert Pattinson", "Ben Affleck", "George Clooney"] },
  { t: "Movie Franchises", c: "Movies", i: ["Star Wars", "Marvel", "Harry Potter", "James Bond", "Transformers"] },
  { t: "Film Genres", c: "Movies", i: ["Action", "Comedy", "Thriller", "Drama", "Musical"] },
  { t: "DC Movies", c: "Movies", i: ["The Dark Knight", "Wonder Woman", "Man of Steel", "Aquaman", "Justice League"] },
  { t: "Animation Studios", c: "Movies", i: ["Pixar", "Studio Ghibli", "Disney Animation", "DreamWorks", "Illumination"] },
  { t: "Fast and Furious Movies", c: "Movies", i: ["Fast Five", "Furious 7", "Fast & Furious 6", "The Fast and the Furious", "Tokyo Drift"] },
  { t: "Harry Potter Movies", c: "Movies", i: ["Prisoner of Azkaban", "Deathly Hallows Part 2", "Goblet of Fire", "Sorcerer's Stone", "Chamber of Secrets"] },
  { t: "Lord of the Rings Movies", c: "Movies", i: ["Return of the King", "Fellowship of the Ring", "The Two Towers", "An Unexpected Journey", "Battle of Five Armies"] },
  { t: "Movie Theater Snacks", c: "Movies", i: ["Popcorn", "Nachos", "Sour Patch Kids", "Slushies", "Hot Dogs"] },
  { t: "James Bond Actors", c: "Movies", i: ["Sean Connery", "Daniel Craig", "Pierce Brosnan", "Roger Moore", "George Lazenby"] },
  { t: "Sci-Fi Movies", c: "Movies", i: ["The Matrix", "Blade Runner", "Interstellar", "Arrival", "Dune"] },
  { t: "Romantic Comedies", c: "Movies", i: ["When Harry Met Sally", "Pretty Woman", "Notting Hill", "The Proposal", "27 Dresses"] },
  { t: "Movie Studios", c: "Movies", i: ["Warner Bros", "Disney", "Universal", "Paramount", "Sony Pictures"] },
  { t: "Jurassic Park Movies", c: "Movies", i: ["Jurassic Park", "The Lost World", "Jurassic World", "Fallen Kingdom", "Dominion"] },
  { t: "Sports Movies", c: "Movies", i: ["Rocky", "Remember the Titans", "Space Jam", "The Blind Side", "Talladega Nights"] },
  { t: "Heist Movies", c: "Movies", i: ["Heat", "Ocean's Eleven", "The Italian Job", "Baby Driver", "Now You See Me"] },
  { t: "Film Directors", c: "Movies", i: ["Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "Martin Scorsese", "Michael Bay"] },
  { t: "Toy Story Movies", c: "Movies", i: ["Toy Story 3", "Toy Story", "Toy Story 2", "Toy Story 4", "Lightyear"] },
  { t: "Zombie Movies", c: "Movies", i: ["Shaun of the Dead", "28 Days Later", "Dawn of the Dead", "Zombieland", "World War Z"] },
  { t: "Sitcoms", c: "TV", i: ["The Office", "Friends", "Seinfeld", "Parks and Rec", "The Big Bang Theory"] },
  { t: "Netflix Originals", c: "TV", i: ["Stranger Things", "Squid Game", "Wednesday", "Bridgerton", "Emily in Paris"] },
  { t: "Reality TV Shows", c: "TV", i: ["Survivor", "The Bachelor", "Big Brother", "Love Island", "Jersey Shore"] },
  { t: "Cartoons", c: "TV", i: ["SpongeBob SquarePants", "Avatar", "Tom and Jerry", "Scooby-Doo", "Teen Titans Go"] },
  { t: "Cooking Shows", c: "TV", i: ["Great British Bake Off", "MasterChef", "Hell's Kitchen", "Iron Chef", "Chopped"] },
  { t: "Crime Dramas", c: "TV", i: ["Breaking Bad", "The Wire", "True Detective", "Law & Order", "CSI"] },
  { t: "Teen Shows", c: "TV", i: ["Gossip Girl", "Glee", "Outer Banks", "Riverdale", "13 Reasons Why"] },
  { t: "Adult Animated Series", c: "TV", i: ["The Simpsons", "South Park", "Rick and Morty", "Family Guy", "American Dad"] },
  { t: "Game Shows", c: "TV", i: ["Jeopardy", "Wheel of Fortune", "Price Is Right", "Family Feud", "Deal or No Deal"] },
  { t: "HBO Dramas", c: "TV", i: ["The Sopranos", "Game of Thrones", "Succession", "Westworld", "Euphoria"] },
  { t: "Talk Shows", c: "TV", i: ["Oprah", "The Daily Show", "Jimmy Kimmel Live", "Ellen", "The View"] },
  { t: "Medical Dramas", c: "TV", i: ["ER", "House", "Grey's Anatomy", "Scrubs", "Chicago Med"] },
  { t: "Nature Documentaries", c: "TV", i: ["Planet Earth", "Blue Planet", "Our Planet", "Frozen Planet", "Life"] },
  { t: "Anime Series", c: "TV", i: ["Attack on Titan", "One Piece", "Naruto", "Dragon Ball Z", "Bleach"] },
  { t: "Fantasy Shows", c: "TV", i: ["Game of Thrones", "House of the Dragon", "The Witcher", "Shadow and Bone", "The Wheel of Time"] },
  { t: "Late Night Hosts", c: "TV", i: ["David Letterman", "Conan O'Brien", "Stephen Colbert", "Jimmy Fallon", "James Corden"] },
  { t: "Kids Shows", c: "TV", i: ["Sesame Street", "Bluey", "Paw Patrol", "Dora the Explorer", "Caillou"] },
  { t: "Sci-Fi Shows", c: "TV", i: ["The X-Files", "Black Mirror", "The Mandalorian", "Doctor Who", "Lost"] },
  { t: "Talent Competition Shows", c: "TV", i: ["American Idol", "The Voice", "America's Got Talent", "Dancing with the Stars", "The Masked Singer"] },
  { t: "British TV Shows", c: "TV", i: ["Sherlock", "Peaky Blinders", "The Crown", "Downton Abbey", "Top Gear"] },
  { t: "Legal Dramas", c: "TV", i: ["Better Call Saul", "The Good Wife", "Suits", "Boston Legal", "Ally McBeal"] },
  { t: "Star Trek Series", c: "TV", i: ["The Next Generation", "Deep Space Nine", "The Original Series", "Voyager", "Enterprise"] },
  { t: "Soap Operas", c: "TV", i: ["General Hospital", "Days of Our Lives", "The Young and Restless", "As the World Turns", "Passions"] },
  { t: "Superhero Shows", c: "TV", i: ["Daredevil", "The Boys", "The Flash", "Arrow", "Inhumans"] },
  { t: "Music Genres", c: "Music", i: ["Hip Hop", "Rock", "Pop", "Country", "Jazz"] },
  { t: "Music Decades", c: "Music", i: ["The 90s", "The 80s", "The 70s", "The 2000s", "The 2010s"] },
  { t: "Boy Bands", c: "Music", i: ["BTS", "Backstreet Boys", "NSYNC", "One Direction", "Jonas Brothers"] },
  { t: "Karaoke Songs", c: "Music", i: ["Don't Stop Believin'", "Bohemian Rhapsody", "Sweet Caroline", "Livin' on a Prayer", "Wonderwall"] },
  { t: "Christmas Songs", c: "Music", i: ["Last Christmas", "White Christmas", "Jingle Bell Rock", "Feliz Navidad", "Santa Baby"] },
  { t: "Music Streaming Platforms", c: "Music", i: ["Spotify", "Apple Music", "YouTube Music", "Amazon Music", "Tidal"] },
  { t: "Music Festivals", c: "Music", i: ["Glastonbury", "Coachella", "Lollapalooza", "Bonnaroo", "Ultra Music Festival"] },
  { t: "Album Formats", c: "Music", i: ["Vinyl", "Streaming", "CD", "Cassette", "8-Track"] },
  { t: "Rock Bands", c: "Music", i: ["The Beatles", "Led Zeppelin", "Queen", "Nirvana", "Nickelback"] },
  { t: "Pop Stars", c: "Music", i: ["Michael Jackson", "Beyonce", "Taylor Swift", "Ariana Grande", "Justin Bieber"] },
  { t: "Rap Artists", c: "Music", i: ["Kendrick Lamar", "Jay-Z", "Eminem", "Drake", "Post Malone"] },
  { t: "Country Artists", c: "Music", i: ["Johnny Cash", "Dolly Parton", "Garth Brooks", "Shania Twain", "Luke Bryan"] },
  { t: "Music Awards", c: "Music", i: ["Grammy Awards", "Brit Awards", "Billboard Music Awards", "American Music Awards", "MTV VMAs"] },
  { t: "Guitar Brands", c: "Music", i: ["Fender", "Gibson", "Martin", "Ibanez", "Squier"] },
  { t: "Concert Venues", c: "Music", i: ["Madison Square Garden", "Red Rocks", "Wembley Stadium", "The Hollywood Bowl", "The Sphere"] },
  { t: "Wedding Songs", c: "Music", i: ["At Last", "Perfect", "Thinking Out Loud", "Marry You", "Cha Cha Slide"] },
  { t: "Road Trip Songs", c: "Music", i: ["Country Roads", "Life Is a Highway", "Africa", "Take It Easy", "Mr. Brightside"] },
  { t: "Girl Groups", c: "Music", i: ["Destiny's Child", "TLC", "Spice Girls", "Little Mix", "Fifth Harmony"] },
  { t: "Metal Bands", c: "Music", i: ["Metallica", "Black Sabbath", "Iron Maiden", "Slipknot", "Limp Bizkit"] },
  { t: "Disney Songs", c: "Music", i: ["Circle of Life", "A Whole New World", "Let It Go", "Under the Sea", "Hakuna Matata"] },
  { t: "Movie Soundtracks", c: "Music", i: ["Star Wars", "The Lion King", "Guardians of the Galaxy", "Pulp Fiction", "Top Gun"] },
  { t: "Latin Music Genres", c: "Music", i: ["Reggaeton", "Salsa", "Bachata", "Cumbia", "Merengue"] },
  { t: "Workout Songs", c: "Music", i: ["Eye of the Tiger", "Lose Yourself", "Till I Collapse", "Stronger", "Thunderstruck"] },
  { t: "Sneaker Brands", c: "Fashion", i: ["Nike", "Adidas", "New Balance", "Puma", "Reebok"] },
  { t: "Clothing Brands", c: "Fashion", i: ["Levi's", "Uniqlo", "Ralph Lauren", "Gap", "Old Navy"] },
  { t: "Jean Styles", c: "Fashion", i: ["Straight Leg", "Slim Fit", "Wide Leg", "Bootcut", "Skinny Jeans"] },
  { t: "Jacket Types", c: "Fashion", i: ["Leather Jacket", "Denim Jacket", "Bomber Jacket", "Puffer Jacket", "Windbreaker"] },
  { t: "Watch Brands", c: "Fashion", i: ["Rolex", "Omega", "Seiko", "Casio", "Fossil"] },
  { t: "Sunglasses Brands", c: "Fashion", i: ["Ray-Ban", "Persol", "Oakley", "Maui Jim", "Warby Parker"] },
  { t: "Handbag Brands", c: "Fashion", i: ["Hermes", "Chanel", "Louis Vuitton", "Gucci", "Michael Kors"] },
  { t: "Footwear Types", c: "Fashion", i: ["Sneakers", "Boots", "Loafers", "Sandals", "Crocs"] },
  { t: "Luxury Fashion Houses", c: "Fashion", i: ["Chanel", "Dior", "Prada", "Versace", "Balenciaga"] },
  { t: "Fast Fashion Brands", c: "Fashion", i: ["Zara", "H&M", "Forever 21", "Boohoo", "Shein"] },
  { t: "Athletic Wear Brands", c: "Fashion", i: ["Nike", "Lululemon", "Adidas", "Under Armour", "Fabletics"] },
  { t: "Hat Styles", c: "Fashion", i: ["Baseball Cap", "Beanie", "Bucket Hat", "Fedora", "Trucker Hat"] },
  { t: "Winter Wardrobe Staples", c: "Fashion", i: ["Wool Coat", "Scarf", "Gloves", "Thermal Socks", "Ear Muffs"] },
  { t: "Denim Brands", c: "Fashion", i: ["Levi's", "Wrangler", "Lee", "Diesel", "True Religion"] },
  { t: "Boot Styles", c: "Fashion", i: ["Chelsea Boots", "Combat Boots", "Cowboy Boots", "Chukka Boots", "Ugg Boots"] },
  { t: "Fashion Accessories", c: "Fashion", i: ["Watch", "Belt", "Scarf", "Rings", "Fanny Pack"] },
  { t: "Outerwear Brands", c: "Fashion", i: ["The North Face", "Patagonia", "Canada Goose", "Columbia", "Land's End"] },
  { t: "Formal Wear Pieces", c: "Fashion", i: ["Tailored Suit", "Tuxedo", "Dress Shirt", "Bow Tie", "Cummerbund"] },
  { t: "Summer Wardrobe Staples", c: "Fashion", i: ["Linen Shirt", "Sundress", "Shorts", "Sandals", "Tank Top"] },
  { t: "Sock Styles", c: "Fashion", i: ["Crew Socks", "Ankle Socks", "No-Show Socks", "Knee Highs", "Toe Socks"] },
  { t: "Perfume Brands", c: "Fashion", i: ["Chanel", "Dior", "Tom Ford", "Versace", "Axe"] },
  { t: "Streetwear Brands", c: "Fashion", i: ["Supreme", "Stussy", "Bape", "Off-White", "Palace"] },
  { t: "Backpack Brands", c: "Fashion", i: ["Herschel", "Fjallraven", "Osprey", "JanSport", "Eastpak"] },
  { t: "Dress Styles", c: "Fashion", i: ["Little Black Dress", "Maxi Dress", "Wrap Dress", "Slip Dress", "Shift Dress"] },
  { t: "Jewelry Types", c: "Fashion", i: ["Watches", "Necklaces", "Earrings", "Bracelets", "Anklets"] },
  { t: "World Cup Winners", c: "World Cup", i: ["Brazil", "Germany", "Italy", "Argentina", "England"] },
  { t: "Football Nations", c: "World Cup", i: ["Brazil", "France", "Spain", "Netherlands", "Wales"] },
  { t: "European Football Clubs", c: "World Cup", i: ["Real Madrid", "Barcelona", "Bayern Munich", "Manchester United", "Ajax"] },
  { t: "Football Leagues", c: "World Cup", i: ["Premier League", "La Liga", "Bundesliga", "Serie A", "Ligue 1"] },
  { t: "Greatest Footballers", c: "World Cup", i: ["Pele", "Maradona", "Messi", "Ronaldo", "Zidane"] },
  { t: "Football Positions", c: "World Cup", i: ["Striker", "Winger", "Midfielder", "Center Back", "Goalkeeper"] },
  { t: "World Cup Host Countries", c: "World Cup", i: ["Brazil", "Germany", "France", "South Africa", "Qatar"] },
  { t: "Football Stadiums", c: "World Cup", i: ["Maracana", "Camp Nou", "Wembley", "San Siro", "Old Trafford"] },
  { t: "International Tournaments", c: "World Cup", i: ["World Cup", "Euros", "Copa America", "Champions League", "Gold Cup"] },
  { t: "South American Teams", c: "World Cup", i: ["Brazil", "Argentina", "Uruguay", "Colombia", "Bolivia"] },
  { t: "European National Teams", c: "World Cup", i: ["France", "Germany", "Spain", "Italy", "Norway"] },
  { t: "African National Teams", c: "World Cup", i: ["Morocco", "Senegal", "Nigeria", "Ghana", "Egypt"] },
  { t: "Asian National Teams", c: "World Cup", i: ["Japan", "South Korea", "Australia", "Iran", "China"] },
  { t: "Premier League Clubs", c: "World Cup", i: ["Manchester City", "Liverpool", "Arsenal", "Chelsea", "Everton"] },
  { t: "National Team Kits", c: "World Cup", i: ["Brazil Yellow", "Netherlands Orange", "Argentina Stripes", "Italy Blue", "Germany White"] },
  { t: "World Cup Goalkeepers", c: "World Cup", i: ["Buffon", "Casillas", "Neuer", "Kahn", "Barthez"] },
  { t: "Football Strikers", c: "World Cup", i: ["Ronaldo Nazario", "Van Basten", "Henry", "Lewandowski", "Drogba"] },
  { t: "Spanish Clubs", c: "World Cup", i: ["Real Madrid", "Barcelona", "Atletico Madrid", "Sevilla", "Valencia"] },
  { t: "Italian Clubs", c: "World Cup", i: ["Juventus", "AC Milan", "Inter Milan", "Napoli", "Roma"] },
  { t: "Football Rivalries", c: "World Cup", i: ["El Clasico", "Brazil Argentina", "Milan Derby", "North London Derby", "Old Firm"] },
  { t: "Football Trophies", c: "World Cup", i: ["World Cup", "Champions League", "Ballon d'Or", "Euros", "Club World Cup"] },
  { t: "Football Boots Brands", c: "World Cup", i: ["Nike", "Adidas", "Puma", "New Balance", "Umbro"] },
  { t: "World Cup Moments", c: "World Cup", i: ["Hand of God", "Zidane Headbutt", "Maracanazo", "Germany 7-1 Brazil", "Suarez Handball"] },
  { t: "Football Managers", c: "World Cup", i: ["Ferguson", "Guardiola", "Mourinho", "Ancelotti", "Klopp"] },
  { t: "World Cup Mascots", c: "World Cup", i: ["Zakumi", "Fuleco", "Naranjito", "Footix", "La'eeb"] },
  { t: "Popular Sports", c: "Sports", i: ["Football", "Basketball", "Soccer", "Tennis", "Golf"] },
  { t: "Olympic Sports", c: "Sports", i: ["Swimming", "Track", "Gymnastics", "Basketball", "Race Walking"] },
  { t: "Winter Sports", c: "Sports", i: ["Skiing", "Snowboarding", "Ice Hockey", "Figure Skating", "Curling"] },
  { t: "Combat Sports", c: "Sports", i: ["Boxing", "MMA", "Wrestling", "Judo", "Fencing"] },
  { t: "Racket Sports", c: "Sports", i: ["Tennis", "Badminton", "Table Tennis", "Squash", "Pickleball"] },
  { t: "Water Sports", c: "Sports", i: ["Swimming", "Surfing", "Water Polo", "Rowing", "Synchronized Swimming"] },
  { t: "Sports Leagues", c: "Sports", i: ["NFL", "NBA", "Premier League", "MLB", "NHL"] },
  { t: "Gym Exercises", c: "Sports", i: ["Squat", "Deadlift", "Bench Press", "Pull Up", "Burpee"] },
  { t: "Running Distances", c: "Sports", i: ["100m", "Marathon", "5K", "800m", "Mile"] },
  { t: "Track and Field Events", c: "Sports", i: ["100m Sprint", "High Jump", "Long Jump", "Pole Vault", "Shot Put"] },
  { t: "Sports Equipment", c: "Sports", i: ["Basketball", "Tennis Racket", "Golf Clubs", "Hockey Stick", "Jump Rope"] },
  { t: "Individual Sports", c: "Sports", i: ["Tennis", "Golf", "Boxing", "Cycling", "Archery"] },
  { t: "Sportswear Brands", c: "Sports", i: ["Nike", "Adidas", "Under Armour", "Puma", "Reebok"] },
  { t: "Motorsports", c: "Sports", i: ["Formula 1", "MotoGP", "NASCAR", "Rally", "Drag Racing"] },
  { t: "Extreme Sports", c: "Sports", i: ["Skateboarding", "Snowboarding", "Surfing", "BMX", "Base Jumping"] },
  { t: "Tennis Grand Slams", c: "Sports", i: ["Wimbledon", "US Open", "French Open", "Australian Open", "Davis Cup"] },
  { t: "Greatest Athletes", c: "Sports", i: ["Jordan", "Ali", "Messi", "Serena Williams", "Bolt"] },
  { t: "Cardio Machines", c: "Sports", i: ["Treadmill", "Rowing Machine", "Stair Climber", "Elliptical", "Stationary Bike"] },
  { t: "Golf Majors", c: "Sports", i: ["The Masters", "US Open", "The Open", "PGA Championship", "Ryder Cup"] },
  { t: "Sports Drinks", c: "Sports", i: ["Gatorade", "Powerade", "Water", "Coconut Water", "Vitamin Water"] },
  { t: "Boxing Legends", c: "Sports", i: ["Muhammad Ali", "Mike Tyson", "Sugar Ray Robinson", "Floyd Mayweather", "Rocky Marciano"] },
  { t: "Backyard Games", c: "Sports", i: ["Cornhole", "Horseshoes", "Badminton", "Croquet", "Lawn Darts"] },
  { t: "Stadium Foods", c: "Sports", i: ["Hot Dog", "Nachos", "Pretzel", "Popcorn", "Cotton Candy"] },
  { t: "NBA Teams", c: "Basketball", i: ["Lakers", "Celtics", "Bulls", "Warriors", "Hornets"] },
  { t: "NBA Legends", c: "Basketball", i: ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar", "Magic Johnson", "Larry Bird"] },
  { t: "Basketball Positions", c: "Basketball", i: ["Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center"] },
  { t: "Basketball Shoes", c: "Basketball", i: ["Air Jordan 1", "Kobe 6", "LeBron 8", "Kyrie 4", "Converse Weapon"] },
  { t: "Shot Types", c: "Basketball", i: ["Dunk", "Three Pointer", "Layup", "Fadeaway", "Free Throw"] },
  { t: "Dunk Types", c: "Basketball", i: ["Windmill", "Tomahawk", "360 Dunk", "Alley Oop", "Two Hand Slam"] },
  { t: "College Basketball Programs", c: "Basketball", i: ["Duke", "Kentucky", "North Carolina", "Kansas", "UCLA"] },
  { t: "NBA Cities", c: "Basketball", i: ["Los Angeles", "New York", "Chicago", "Boston", "Memphis"] },
  { t: "NBA Point Guards", c: "Basketball", i: ["Magic Johnson", "Stephen Curry", "Steve Nash", "Chris Paul", "Isiah Thomas"] },
  { t: "NBA Centers", c: "Basketball", i: ["Kareem Abdul-Jabbar", "Shaquille O'Neal", "Hakeem Olajuwon", "Bill Russell", "Yao Ming"] },
  { t: "Basketball Movies", c: "Basketball", i: ["Hoosiers", "Space Jam", "He Got Game", "White Men Can't Jump", "Coach Carter"] },
  { t: "NBA Jerseys", c: "Basketball", i: ["Bulls Red", "Lakers Gold", "Celtics Green", "Raptors Purple", "Nuggets Rainbow"] },
  { t: "NBA Arenas", c: "Basketball", i: ["Madison Square Garden", "Boston Garden", "Staples Center", "United Center", "Oracle Arena"] },
  { t: "NBA Dynasties", c: "Basketball", i: ["90s Bulls", "80s Lakers", "60s Celtics", "Warriors", "Heat Big Three"] },
  { t: "Basketball Skills", c: "Basketball", i: ["Shooting", "Passing", "Ball Handling", "Rebounding", "Defense"] },
  { t: "NBA Awards", c: "Basketball", i: ["MVP", "Finals MVP", "Defensive Player", "Rookie of the Year", "Sixth Man"] },
  { t: "Streetball Courts", c: "Basketball", i: ["Rucker Park", "Venice Beach", "The Cage", "Dyckman Park", "Local YMCA"] },
  { t: "NBA Nicknames", c: "Basketball", i: ["Air Jordan", "The King", "Black Mamba", "The Answer", "The Greek Freak"] },
  { t: "Basketball Moves", c: "Basketball", i: ["Crossover", "Euro Step", "Step Back", "Spin Move", "Pump Fake"] },
  { t: "NBA Rivalries", c: "Basketball", i: ["Lakers Celtics", "Bulls Pistons", "Heat Spurs", "Knicks Pacers", "Clippers Lakers"] },
  { t: "Basketball Leagues", c: "Basketball", i: ["NBA", "EuroLeague", "NCAA", "WNBA", "G League"] },
  { t: "NBA Draft Picks", c: "Basketball", i: ["LeBron James", "Tim Duncan", "Shaquille O'Neal", "Allen Iverson", "Anthony Bennett"] },
  { t: "Basketball Court Spots", c: "Basketball", i: ["Corner Three", "Top of Key", "Free Throw Line", "Post", "Half Court"] },
  { t: "NBA Sneaker Brands", c: "Basketball", i: ["Nike", "Jordan Brand", "Adidas", "Puma", "Anta"] },
  { t: "Olympic Basketball Teams", c: "Basketball", i: ["USA", "Spain", "Argentina", "Serbia", "Nigeria"] },
  { t: "Luxury Car Brands", c: "Cars", i: ["Rolls-Royce", "Bentley", "Mercedes-Benz", "Lexus", "Cadillac"] },
  { t: "Sports Cars", c: "Cars", i: ["Porsche 911", "Corvette", "Nissan GT-R", "Mazda MX-5", "Toyota Supra"] },
  { t: "Muscle Cars", c: "Cars", i: ["Ford Mustang", "Chevrolet Camaro", "Dodge Challenger", "Pontiac GTO", "AMC Javelin"] },
  { t: "Electric Cars", c: "Cars", i: ["Tesla Model 3", "Hyundai Ioniq 5", "Ford Mustang Mach-E", "Chevrolet Bolt", "Nissan Leaf"] },
  { t: "Pickup Trucks", c: "Cars", i: ["Ford F-150", "Toyota Tacoma", "Chevrolet Silverado", "Ram 1500", "Nissan Frontier"] },
  { t: "SUV Models", c: "Cars", i: ["Toyota RAV4", "Honda CR-V", "Jeep Wrangler", "Ford Explorer", "Nissan Rogue"] },
  { t: "Supercar Brands", c: "Cars", i: ["Ferrari", "Lamborghini", "McLaren", "Bugatti", "Koenigsegg"] },
  { t: "Motorcycle Brands", c: "Cars", i: ["Honda", "Yamaha", "Harley-Davidson", "Ducati", "Kawasaki"] },
  { t: "Car Colors", c: "Cars", i: ["Black", "White", "Red", "Silver", "Beige"] },
  { t: "First Cars", c: "Cars", i: ["Honda Civic", "Toyota Corolla", "Ford Focus", "Volkswagen Golf", "Chevrolet Cavalier"] },
  { t: "Road Trip Cars", c: "Cars", i: ["Toyota Land Cruiser", "Honda Odyssey", "Subaru Outback", "Ford Bronco", "Smart Car"] },
  { t: "German Car Brands", c: "Cars", i: ["Porsche", "BMW", "Mercedes-Benz", "Audi", "Volkswagen"] },
  { t: "Japanese Car Brands", c: "Cars", i: ["Toyota", "Honda", "Mazda", "Subaru", "Mitsubishi"] },
  { t: "American Car Brands", c: "Cars", i: ["Ford", "Chevrolet", "Jeep", "Dodge", "Chrysler"] },
  { t: "Italian Car Brands", c: "Cars", i: ["Ferrari", "Lamborghini", "Maserati", "Alfa Romeo", "Fiat"] },
  { t: "Classic Cars", c: "Cars", i: ["Ford Model T", "VW Beetle", "Mini Cooper", "Citroen 2CV", "Trabant"] },
  { t: "Off Road Vehicles", c: "Cars", i: ["Jeep Wrangler", "Land Rover Defender", "Toyota 4Runner", "Ford Bronco", "Hummer"] },
  { t: "Family Cars", c: "Cars", i: ["Honda Odyssey", "Toyota Sienna", "Chrysler Pacifica", "Kia Carnival", "Station Wagon"] },
  { t: "Transmission Types", c: "Cars", i: ["Manual", "Dual Clutch", "Automatic", "CVT", "Automated Manual"] },
  { t: "Car Features", c: "Cars", i: ["Air Conditioning", "Heated Seats", "Sunroof", "Backup Camera", "Cup Holders"] },
  { t: "Racing Cars", c: "Cars", i: ["Formula 1 Car", "Le Mans Prototype", "Rally Car", "NASCAR Stock Car", "Go Kart"] },
  { t: "Car Movies", c: "Cars", i: ["Bullitt", "Mad Max Fury Road", "Fast and Furious", "Ford v Ferrari", "Cars"] },
  { t: "Tire Brands", c: "Cars", i: ["Michelin", "Bridgestone", "Goodyear", "Pirelli", "Continental"] },
  { t: "Engine Types", c: "Cars", i: ["V8", "V6", "Inline Six", "Flat Four", "Three Cylinder"] },
];
